//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBicycleRedirectionService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICacheService")]
    public interface ICacheService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getResultFromRequest", ReplyAction="http://tempuri.org/ICacheService/getResultFromRequestResponse")]
        string getResultFromRequest(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getResultFromRequest", ReplyAction="http://tempuri.org/ICacheService/getResultFromRequestResponse")]
        System.Threading.Tasks.Task<string> getResultFromRequestAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getResultFromRequestWithTimeLimit", ReplyAction="http://tempuri.org/ICacheService/getResultFromRequestWithTimeLimitResponse")]
        string getResultFromRequestWithTimeLimit(string request, double timeLimit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getResultFromRequestWithTimeLimit", ReplyAction="http://tempuri.org/ICacheService/getResultFromRequestWithTimeLimitResponse")]
        System.Threading.Tasks.Task<string> getResultFromRequestWithTimeLimitAsync(string request, double timeLimit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICacheServiceChannel : MyBicycleRedirectionService.ServiceReference1.ICacheService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CacheServiceClient : System.ServiceModel.ClientBase<MyBicycleRedirectionService.ServiceReference1.ICacheService>, MyBicycleRedirectionService.ServiceReference1.ICacheService {
        
        public CacheServiceClient() {
        }
        
        public CacheServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CacheServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getResultFromRequest(string request) {
            return base.Channel.getResultFromRequest(request);
        }
        
        public System.Threading.Tasks.Task<string> getResultFromRequestAsync(string request) {
            return base.Channel.getResultFromRequestAsync(request);
        }
        
        public string getResultFromRequestWithTimeLimit(string request, double timeLimit) {
            return base.Channel.getResultFromRequestWithTimeLimit(request, timeLimit);
        }
        
        public System.Threading.Tasks.Task<string> getResultFromRequestWithTimeLimitAsync(string request, double timeLimit) {
            return base.Channel.getResultFromRequestWithTimeLimitAsync(request, timeLimit);
        }
    }
}
